[package]
name = "wave_to_flac"
version = "0.1.0"
edition = "2024"

[dependencies]
rfd = "0.15.2"
hound = "3.5"
flacenc = "0.4.0"
regex = "1.11.1"
encoding_rs = "0.8.35"
encoding_rs_io = "0.1.7"
image = "0.25.5"  # 画像処理ライブラリ
